export default [
    {
        id: 1,
        image:  `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'AnubisSecret'
    }, {
        id: 2,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 3,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 4,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 5,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 6,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 7,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 8,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 9,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 10,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 11,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 12,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 13,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 14,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 15,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 16,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 17,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 18,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 19,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 20,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }, {
        id: 21,
        image: `${require('../../assets/images/games/AnubisSecret.jpg')}`,
        title: 'Game'
    }
]