export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const LOAD_MORE_GAMES_REQUEST = 'LOAD_MORE_GAMES_REQUEST';
export const LOAD_MORE_GAMES_SUCCESS = 'LOAD_MORE_GAMES_SUCCESS';
export const LOAD_MORE_GAMES_FAILURE = 'LOAD_MORE_GAMES_FAILURE';
